export const GET_EVENT_CATEGORY_REQUEST = 'GET_EVENT_CATEGORY_REQUEST';
export const GET_EVENT_CATEGORY_SUCCESS = 'GET_EVENT_CATEGORY_SUCCESS';
export const GET_EVENT_CATEGORY_FAILURE = 'GET_EVENT_CATEGORY_FAILURE';

export const GET_WORKSHOP_CATEGORY_REQUEST = 'GET_WORKSHOP_CATEGORY_REQUEST';
export const GET_WORKSHOP_CATEGORY_SUCCESS = 'GET_WORKSHOP_CATEGORY_SUCCESS';
export const GET_WORKSHOP_CATEGORY_FAILURE = 'GET_WORKSHOP_CATEGORY_FAILURE';

export const GET_CACHED_EVENT_CATEGORY = 'GET_CACHED_EVENT_CATEGORY';

export const GET_CACHED_WORKSHOP_CATEGORY = 'GET_CACHED_WORKSHOP_CATEGORY';

export const ADD_EVENT_CATEGORY_REQUEST = 'ADD_EVENT_CATEGORY_REQUEST';
export const ADD_EVENT_CATEGORY_SUCCESS = 'ADD_EVENT_CATEGORY_SUCCESS';
export const ADD_EVENT_CATEGORY_FAILURE = 'ADD_EVENT_CATEGORY_FAILURE';

export const EDIT_EVENT_CATEGORY_REQUEST = 'EDIT_EVENT_CATEGORY_REQUEST';
export const EDIT_EVENT_CATEGORY_SUCCESS = 'EDIT_EVENT_CATEGORY_SUCCESS';
export const EDIT_EVENT_CATEGORY_FAILURE = 'EDIT_EVENT_CATEGORY_FAILURE';

export const DELETE_EVENT_CATEGORY_REQUEST = 'DELETE_EVENT_CATEGORY_REQUEST';
export const DELETE_EVENT_CATEGORY_SUCCESS = 'DELETE_EVENT_CATEGORY_SUCCESS';
export const DELETE_EVENT_CATEGORY_FAILURE = 'DELETE_EVENT_CATEGORY_FAILURE';

export const ADD_WORKSHOP_CATEGORY_REQUEST = 'ADD_WORKSHOP_CATEGORY_REQUEST';
export const ADD_WORKSHOP_CATEGORY_SUCCESS = 'ADD_WORKSHOP_CATEGORY_SUCCESS';
export const ADD_WORKSHOP_CATEGORY_FAILURE = 'ADD_WORKSHOP_CATEGORY_FAILURE';

export const EDIT_WORKSHOP_CATEGORY_REQUEST = 'EDIT_WORKSHOP_CATEGORY_REQUEST';
export const EDIT_WORKSHOP_CATEGORY_SUCCESS = 'EDIT_WORKSHOP_CATEGORY_SUCCESS';
export const EDIT_WORKSHOP_CATEGORY_FAILURE = 'EDIT_WORKSHOP_CATEGORY_FAILURE';

export const DELETE_WORKSHOP_CATEGORY_REQUEST = 'DELETE_WORKSHOP_CATEGORY_REQUEST';
export const DELETE_WORKSHOP_CATEGORY_SUCCESS = 'DELETE_WORKSHOP_CATEGORY_SUCCESS';
export const DELETE_WORKSHOP_CATEGORY_FAILURE = 'DELETE_WORKSHOP_CATEGORY_FAILURE';
