export const GET_EVENT_CATEGORY = 'GET_EVENT_CATEGORY';
export const GET_WORKSHOP_CATEGORY = 'GET_WORKSHOP_CATEGORY';
export const GET_CACHED_EVENT_CATEGORY = 'GET_CACHED_EVENT_CATEGORY';
export const GET_CACHED_WORKSHOP_CATEGORY = 'GET_CACHED_WORKSHOP_CATEGORY';

export const ADD_EVENT_CATEGORY = 'ADD_EVENT_CATEGORY';
export const EDIT_EVENT_CATEGORY = 'EDIT_EVENT_CATEGORY';
export const DELETE_EVENT_CATEGORY = 'DELETE_EVENT_CATEGORY';

export const ADD_WORKSHOP_CATEGORY = 'ADD_WORKSHOP_CATEGORY';
export const EDIT_WORKSHOP_CATEGORY = 'EDIT_WORKSHOP_CATEGORY';
export const DELETE_WORKSHOP_CATEGORY = 'DELETE_WORKSHOP_CATEGORY';