export const GET_DEMANDS_REQUEST = 'GET_DEMANDS_REQUEST';
export const GET_DEMANDS_SUCCESS = 'GET_DEMANDS_SUCCESS';
export const GET_DEMANDS_FAILURE = 'GET_DEMANDS_FAILURE';

export const GET_DEMAND_REQUEST = 'GET_DEMAND_REQUEST';
export const GET_DEMAND_SUCCESS = 'GET_DEMAND_SUCCESS';
export const GET_DEMAND_FAILURE = 'GET_DEMAND_FAILURE';

export const UPDATE_DEMAND_REQUEST = 'UPDATE_DEMAND_REQUEST';
export const UPDATE_DEMAND_SUCCESS = 'UPDATE_DEMAND_SUCCESS';
export const UPDATE_DEMAND_FAILURE = 'UPDATE_DEMAND_FAILURE';

export const DELETE_DEMAND_REQUEST = 'DELETE_DEMAND_REQUEST';
export const DELETE_DEMAND_SUCCESS = 'DELETE_DEMAND_SUCCESS';
export const DELETE_DEMAND_FAILURE = 'DELETE_DEMAND_FAILURE';

export const GET_ALL_DEMANDS_REQUEST = 'GET_ALL_DEMANDS_REQUEST';
export const GET_ALL_DEMANDS_SUCCESS = 'GET_ALL_DEMANDS_SUCCESS';
export const GET_ALL_DEMANDS_FAILURE = 'GET_ALL_DEMANDS_FAILURE';

export const APPROVE_DEMAND_REQUEST = 'APPROVE_DEMAND_REQUEST';
export const APPROVE_DEMAND_SUCCESS = 'APPROVE_DEMAND_SUCCESS';
export const APPROVE_DEMAND_FAILURE = 'APPROVE_DEMAND_FAILURE';
