export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

export const GET_INITIAL_EVENTS_REQUEST = 'GET_INITIAL_EVENTS_REQUEST';
export const GET_INITIAL_EVENTS_SUCCESS = 'GET_INITIAL_EVENTS_SUCCESS';
export const GET_INITIAL_EVENTS_FAILURE = 'GET_INITIAL_EVENTS_FAILURE';

export const GET_PAGINATED_EVENTS_REQUEST = 'GET_PAGINATED_EVENTS_REQUEST';
export const GET_PAGINATED_EVENTS_SUCCESS = 'GET_PAGINATED_EVENTS_SUCCESS';
export const GET_PAGINATED_EVENTS_FAILURE = 'GET_PAGINATED_EVENTS_FAILURE';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';
