export const ADD_EVENT = 'ADD_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

export const GET_INITIAL_EVENTS = 'GET_INITIAL_EVENTS';
export const GET_PAGINATED_EVENTS = 'GET_PAGINATED_EVENTS';
export const GET_EVENT = 'GET_EVENT';