export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const SET_USER_INFO = 'SET_USER_INFO';
export const PERMIT_ADMIN_ACCESS = 'PERMIT_ADMIN_ACCESS';

export const CLEAN_CACHE = 'CLEAN_CACHE';
