export const GET_KICKSTARTERS_REQUEST = 'GET_KICKSTARTERS_REQUEST';
export const GET_KICKSTARTERS_SUCCESS = 'GET_KICKSTARTERS_SUCCESS';
export const GET_KICKSTARTERS_FAILURE = 'GET_KICKSTARTERS_FAILURE';

export const GET_KICKSTARTER_REQUEST = 'GET_KICKSTARTER_REQUEST';
export const GET_KICKSTARTER_SUCCESS = 'GET_KICKSTARTER_SUCCESS';
export const GET_KICKSTARTER_FAILURE = 'GET_KICKSTARTER_FAILURE';

export const CREATE_KICKSTARTER_REQUEST = 'CREATE_KICKSTARTER_REQUEST';
export const CREATE_KICKSTARTER_SUCCESS = 'CREATE_KICKSTARTER_SUCCESS';
export const CREATE_KICKSTARTER_FAILURE = 'CREATE_KICKSTARTER_FAILURE';

export const UPDATE_KICKSTARTER_REQUEST = 'UPDATE_KICKSTARTER_REQUEST';
export const UPDATE_KICKSTARTER_SUCCESS = 'UPDATE_KICKSTARTER_SUCCESS';
export const UPDATE_KICKSTARTER_FAILURE = 'UPDATE_KICKSTARTER_FAILURE';

export const DELETE_KICKSTARTER_REQUEST = 'DELETE_KICKSTARTER_REQUEST';
export const DELETE_KICKSTARTER_SUCCESS = 'DELETE_KICKSTARTER_SUCCESS';
export const DELETE_KICKSTARTER_FAILURE = 'DELETE_KICKSTARTER_FAILURE';

export const GET_ALL_KICKSTARTERS_REQUEST = 'GET_ALL_KICKSTARTERS_REQUEST';
export const GET_ALL_KICKSTARTERS_SUCCESS = 'GET_ALL_KICKSTARTERS_SUCCESS';
export const GET_ALL_KICKSTARTERS_FAILURE = 'GET_ALL_KICKSTARTERS_FAILURE';

export const APPROVE_KICKSTARTER_REQUEST = 'APPROVE_KICKSTARTER_REQUEST';
export const APPROVE_KICKSTARTER_SUCCESS = 'APPROVE_KICKSTARTER_SUCCESS';
export const APPROVE_KICKSTARTER_FAILURE = 'APPROVE_KICKSTARTER_FAILURE';
