export const SUBMIT_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';

export const GET_MY_ORDER_REQUEST = 'GET_MY_ORDER_REQUEST';
export const GET_MY_ORDER_SUCCESS = 'GET_MY_ORDER_SUCCESS';
export const GET_MY_ORDER_FAILURE = 'GET_MY_ORDER_FAILURE';

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_FAILURE = 'GET_MY_ORDERS_FAILURE';

export const CANCEL_MY_ORDER_REQUEST = 'CANCEL_MY_ORDER_REQUEST';
export const CANCEL_MY_ORDER_SUCCESS = 'CANCEL_MY_ORDER_SUCCESS';
export const CANCEL_MY_ORDER_FAILURE = 'CANCEL_MY_ORDER_FAILURE';

export const GET_ALL_USER_ORDERS_REQUEST = 'GET_ALL_USER_ORDERS_REQUEST';
export const GET_ALL_USER_ORDERS_SUCCESS = 'GET_ALL_USER_ORDERS_SUCCESS';
export const GET_ALL_USER_ORDERS_FAILURE = 'GET_ALL_USER_ORDERS_FAILURE';

export const GET_DISTINCT_INSTANCES_REQUEST = 'GET_DISTINCT_INSTANCES_REQUEST';
export const GET_DISTINCT_INSTANCES_SUCCESS = 'GET_DISTINCT_INSTANCES_SUCCESS';
export const GET_DISTINCT_INSTANCES_FAILURE = 'GET_DISTINCT_INSTANCES_FAILURE';
