export const SUBMIT_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';

export const GET_ALL_USER_ORDERS_REQUEST = 'GET_ALL_USER_ORDERS_REQUEST';
export const GET_ALL_USER_ORDERS_SUCCESS = 'GET_ALL_USER_ORDERS_SUCCESS';

export const EXPORT_ORDERS_TO_EMAIL_REQUEST = 'EXPORT_ORDERS_TO_EMAIL_REQUEST';
export const EXPORT_ORDERS_TO_EMAIL_SUCCESS = 'EXPORT_ORDERS_TO_EMAIL_SUCCESS';
