export const GET_ALL_PRINTERS_REQUEST = 'GET_ALL_PRINTERS_REQUEST';
export const GET_ALL_PRINTERS_SUCCESS = 'GET_ALL_PRINTERS_SUCCESS';

export const GET_CACHED_PRINTER = 'GET_CACHED_PRINTER';

export const GET_PRINTER_REQUEST = 'GET_PRINTER_REQUEST';
export const GET_PRINTER_SUCCESS = 'GET_PRINTER_SUCCESS';