export const ADD_WORKSHOP = 'ADD_WORKSHOP';
export const EDIT_WORKSHOP = 'EDIT_WORKSHOP';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';

export const GET_ALL_WORKSHOPS = 'GET_ALL_WORKSHOPS';
export const GET_CACHED_WORKSHOP = 'GET_CACHED_WORKSHOP';
export const GET_WORKSHOP = 'GET_WORKSHOP';