export const ADD_WORKSHOP_REQUEST = 'ADD_WORKSHOP_REQUEST';
export const ADD_WORKSHOP_SUCCESS = 'ADD_WORKSHOP_SUCCESS';
export const ADD_WORKSHOP_FAILURE = 'ADD_WORKSHOP_FAILURE';

export const EDIT_WORKSHOP_REQUEST = 'EDIT_WORKSHOP_REQUEST';
export const EDIT_WORKSHOP_SUCCESS = 'EDIT_WORKSHOP_SUCCESS';
export const EDIT_WORKSHOP_FAILURE = 'EDIT_WORKSHOP_FAILURE';

export const DELETE_WORKSHOP_REQUEST = 'DELETE_WORKSHOP_REQUEST';
export const DELETE_WORKSHOP_SUCCESS = 'DELETE_WORKSHOP_SUCCESS';
export const DELETE_WORKSHOP_FAILURE = 'DELETE_WORKSHOP_FAILURE';

export const GET_INITIAL_WORKSHOPS_REQUEST = 'GET_INITIAL_WORKSHOPS_REQUEST';
export const GET_INITIAL_WORKSHOPS_SUCCESS = 'GET_INITIAL_WORKSHOPS_SUCCESS';
export const GET_INITIAL_WORKSHOPS_FAILURE = 'GET_INITIAL_WORKSHOPS_FAILURE';

export const GET_PAGINATED_WORKSHOPS_REQUEST = 'GET_PAGINATED_WORKSHOPS_REQUEST';
export const GET_PAGINATED_WORKSHOPS_SUCCESS = 'GET_PAGINATED_WORKSHOPS_SUCCESS';
export const GET_PAGINATED_WORKSHOPS_FAILURE = 'GET_PAGINATED_WORKSHOPS_FAILURE';

export const GET_WORKSHOP_REQUEST = 'GET_WORKSHOP_REQUEST';
export const GET_WORKSHOP_SUCCESS = 'GET_WORKSHOP_SUCCESS';
export const GET_WORKSHOP_FAILURE = 'GET_WORKSHOP_FAILURE';
