export const ADD_WORKSHOP = 'ADD_WORKSHOP';
export const EDIT_WORKSHOP = 'EDIT_WORKSHOP';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';

export const GET_INITIAL_WORKSHOPS = 'GET_INITIAL_WORKSHOPS';
export const GET_PAGINATED_WORKSHOPS = 'GET_PAGINATED_WORKSHOPS';
export const GET_WORKSHOP = 'GET_WORKSHOP';